In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings("ignore")

In [3]:
data = pd.read_csv("Booking.com_Data_Collected.csv")

In [5]:
data

,Unnamed: 0,Property_name,Location,Rating,Review,Type_of_stay,Stay_duration_and_group_size,price,Taxes_and_charges_inr
0,0,Olive Service Apartments Rohini,"Rohini, New Delhi",9.8,Exceptional,1×Two-Bedroom ApartmentEntire apartment•2 bedr...,"5 nights, 10 adults","₹47,814","5,738"
1,1,Olive Service Apartments - Greater Kailash,"Greater Kailash 1, New Delhi",9.0,Superb,1×Standard Two-Bedroom ApartmentEntire apartme...,"5 nights, 10 adults","₹149,629","26,933"
2,2,Anara Service Apartments - Greater Kailash Par...,New Delhi,8.3,Very good,1×Studio with BalconyEntire studio•1 kitchen•1...,"5 nights, 10 adults","₹152,620",NaN
3,3,Homlee-Excellency Large 4BHK-South Delhi- NFC,"New Friends Colony, New Delhi",8.8,Fabulous,NaN,"5 nights, 10 adults","₹67,250","13,305"
4,4,BedChambers Serviced Apartments South Extension,New Delhi,8.7,Fabulous,2×Three-Bedroom Apartment2 entire apartments•6...,"5 nights, 10 adults","₹144,982",NaN
...,...,...,...,...,...,...,...,...,...
1619,1619,Northern View Haward,Shimla,8.8,Fabulous,5×Deluxe Double Room5 double bedsFree cancella...,"5 nights, 8 adults, 2 children","₹23,726","2,847"
1620,1620,"Treebo Greenland, Mall Road",Shimla,5.3,Review score,2×Economy Double Room2 extra-large double beds...,"5 nights, 8 adults, 2 children","₹55,575","6,669"
1621,1621,Krishna Hill Stay Near Mall Road,Shimla,8.2,Very good,2×Standard Double Room2 double bedsFree cancel...,"5 nights, 8 adults, 2 children","₹26,900","3,228"
1622,1622,Shimla Hills Apartments 2BHK,Shimla,9.0,Superb,2×Two-Bedroom Apartment2 entire apartments•4 b...,"5 nights, 8 adults, 2 children","₹28,000","3,360"
1623,1623,Himalayan Hideaway,Shimla,8.0,Very good,1×Deluxe Family Room6 single bedsFree cancella...,"5 nights, 8 adults, 2 children","₹33,725","4,047"

In [17]:
#get only numerical column
numerical_columns = data.select_dtypes(include=['number'])
numerical_columns.head(19)

    Unnamed: 0  Rating
0            0     9.8
1            1     9.0
2            2     8.3
3            3     8.8
4            4     8.7
5            5     NaN
6            6     7.5
7            7     NaN
8            8     8.4
9            9     7.2
10          10     8.9
11          11     9.0
12          12     9.3
13          13     8.9
14          14     NaN
15          15     NaN
16          16     8.0
17          17     8.0
18          18     8.5

In [19]:
# get only categorical column
categorical_columns = data.select_dtypes(include=['object', 'category'])
categorical_columns.head(18)

,Property_name,Location,Review,Type_of_stay,Stay_duration_and_group_size,price,Taxes_and_charges_inr
0,Olive Service Apartments Rohini,"Rohini, New Delhi",Exceptional,1×Two-Bedroom ApartmentEntire apartment•2 bedr...,"5 nights, 10 adults","₹47,814","5,738"
1,Olive Service Apartments - Greater Kailash,"Greater Kailash 1, New Delhi",Superb,1×Standard Two-Bedroom ApartmentEntire apartme...,"5 nights, 10 adults","₹149,629","26,933"
2,Anara Service Apartments - Greater Kailash Par...,New Delhi,Very good,1×Studio with BalconyEntire studio•1 kitchen•1...,"5 nights, 10 adults","₹152,620",NaN
3,Homlee-Excellency Large 4BHK-South Delhi- NFC,"New Friends Colony, New Delhi",Fabulous,NaN,"5 nights, 10 adults","₹67,250","13,305"
4,BedChambers Serviced Apartments South Extension,New Delhi,Fabulous,2×Three-Bedroom Apartment2 entire apartments•6...,"5 nights, 10 adults","₹144,982",NaN
5,Homlee-Green Luxury 3BHK-South DEL-NFC-Lift,"New Friends Colony, New Delhi",Exceptional,NaN,"5 nights, 10 adults","₹67,250","13,104"
6,Olive Serviced Apartments - Defence Colony,New Delhi,Good,1×Standard StudioEntire studio•1 bathroom•36m²...,"5 nights, 10 adults","₹192,026","34,565"
7,Ideal 3bhk apartment!Downtown,New Delhi,NaN,1×Two-Bedroom ApartmentEntire apartment•2 bedr...,"5 nights, 10 adults","₹50,000",NaN
8,Vista Residences at GK 1 - Air Purifier and Co...,"Greater Kailash 1, New Delhi",Very good,1×ApartmentEntire apartment•3 bedrooms•3 bathr...,"5 nights, 10 adults","₹113,606","17,769"
9,Homlee-Vintage 2BHK-Fort View-Bharat Mandapam-...,"Central Delhi, New Delhi",Good,2×Two-Bedroom Apartment2 entire apartments•4 b...,"5 nights, 10 adults","₹57,490","8,097"
10,Homlee-Anupam 3BHK-Lift-Parking-Saket-Max Hosp...,"South Delhi, New Delhi",Fabulous,NaN,"5 nights, 10 adults","₹57,250","11,304"
11,Homlee-Pentagon 3 BHK luxurious-Lift-Parking-S...,"Saket, New Delhi",Superb,NaN,"5 nights, 10 adults","₹102,500","19,649"
12,StayVista at The Cityscape with Lawn & Pool,"Dwarka, New Delhi",Superb,NaN,"5 nights, 10 adults","₹200,175","36,032"
13,Hyatt Delhi Residences,"Aerocity, New Delhi",Fabulous,1×Two-Bedroom ApartmentEntire apartment•2 bedr...,"5 nights, 10 adults","₹268,000","48,240"
14,StayVista's Anantam - Luxury 4BR villa with Hu...,New Delhi,NaN,NaN,"5 nights, 10 adults","₹354,469","63,804"
15,"Fortune Home Service Apartment 3Bhk,J-171 Saket","Saket, New Delhi",NaN,1×Three-Bedroom Standard ApartmentEntire apart...,"5 nights, 10 adults","₹91,195","27,615"
16,Urban Nest -New 3BHK Apartments,"South Delhi, New Delhi",NaN,1×Three-Bedroom Apartment with BalconyEntire a...,"5 nights, 10 adults","₹149,060","26,831"
17,"Fortune Home Service Apartment 3Bhk,E-28, Sake...","Saket, New Delhi",NaN,1×Three-Bedroom Superior ApartmentEntire apart...,"5 nights, 10 adults","₹81,596","25,596"

In [13]:
#check duplicate rows : Observation :there are no duplicate rows
data.duplicated().sum()

0

In [15]:
# Check the null values
data.isna().sum()

Unnamed: 0                        0
Property_name                     0
Location                          0
Rating                          283
Review                          330
Type_of_stay                    581
Stay_duration_and_group_size      0
price                             0
Taxes_and_charges_inr            19
dtype: int64

In [17]:
# Find the percentage of the null values
# Step 1: Calculate missing value percentage:
missing_percent =data.isnull().mean()*100
missing_percent.sort_values(ascending =False)
#step 2 : Convert to a DataFrame
#missing_df =missing_percent.reset_index()
#missing_df.columns = ["Column" ,"Missing_percentage"]

#Step 3: (optional) Sort by highest missing %
# missing_df =missing_df.sort_values(by="Missing_percentage",ascending =False)
# missing_df

Type_of_stay                    35.775862
Review                          20.320197
Rating                          17.426108
Taxes_and_charges_inr            1.169951
Unnamed: 0                       0.000000
Property_name                    0.000000
Location                         0.000000
Stay_duration_and_group_size     0.000000
price                            0.000000
dtype: float64

In [24]:
#Drop the columns that we dont needed
data.drop("Unnamed: 0" ,axis = 1 ,inplace =True)

In [25]:
data["Property_name"] = data["Property_name"].str.lower()
data["Location"] =data["Location"].str.lower()
data["Review"] =data["Review"].str.lower()
data["Type_of_stay"] =data["Type_of_stay"].str.lower()

In [26]:
data["price"] =data["price"].replace("[\D]" ,"",regex =True).astype(float)
data["Taxes_and_charges_inr"] =data["Taxes_and_charges_inr"].replace("[\D]" ,"",regex =True).astype(float)

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1624 entries, 0 to 1623
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Property_name                 1624 non-null   object
 1   Location                      1624 non-null   object
 2   Rating                        1341 non-null   float64
 3   Review                        1294 non-null   object
 4   Type_of_stay                  1043 non-null   object
 5   Stay_duration_and_group_size  1624 non-null   object
 6   price                         1624 non-null   float64
 7   Taxes_and_charges_inr         1605 non-null   float64
dtypes: float64(3), object(5)
memory usage: 101.6+ KB

In [28]:
data.Taxes_and_charges_inr.unique()

array([ 5738., 26933.,    nan, 13305., 13104., 34565., 17769.,  8097.,
       11304., 19649., 36032., 48240., 63804., 27615., 26831., 25596.,
       24342., 31392.,  9792., 14850.,  7798.,  5170., 15391., 39600.,
       12630., 12114., 10539.,  7587., 13206., 25464., 18749., 34790.,
       30871., 62454., 15110.,  7739., 10206., 11416., 29741., 17580.,
       40815., 11934., 10359., 24384.,  7647., 64314., 14097., 33147.,
        5339.,  5139.,  1924.,  3871.,  7611.,  2432.,  5568.,  2149.,
        1283.,  2646.,  2133.,  2310.,  2662.,  2160., 14400.,  2997.,
        3600.,  2068.,  4749.,  3267.,  3597.,  3839.,  4796., 43920.,
       12204., 10629., 26004., 35357., 62792., 37400.,  7829.,  5319.,
       25090., 16200.,  5940.,  3366.,  3694.,  9000.,  6885.,  2923.,
        3432.,  6600., 13093.,  5328.,  2580.,  8149.,  9745.,  4050.,
        1834.,  3635.,  3793.,  4559.,  4644.,  8304.,  3024.,  5850.,
        1188.,  1350.,  3060.,   720.,  2158.,  1798.,  3033., 10079.,
        2638.,  1670.,  1395.,  5097.,  2038.,  1539., 10125.,  2419.,
        1422.,  4320.,  3056., 23520.,  2569.,  1158.,  4536.,  8506.,
       11520., 15636.,  1870.,  2338., 25920.,  1800.,  4500.,  9900.,
        8774.,  3093.,  3402., 11386.,  5014.,  1710.,  1100., 10632.,
       19320.,  1334.,  1426.,  1942., 13500.,  3828.,  3858., 32400.,
        1302.,  1823.,  1684.,  3515.,  5589., 11190.,  3764.,  5997.,
       16144., 17250.,  3596.,  5040.,  4329., 12240.,  3671.,  1436.,
        3427., 17242.,   998.,  6660.,  3899., 11832.,  2627.,  2621.,
        4130.,  6803.,  3590.,  3030.,  2860.,  3612.,  6443.,  1584.,
        3192.,  5550.,  1092.,  9879., 32130.,  2757.,  2333.,  9717.,
        2928.,  6154., 13260.,  4616.,  3562.,  4752.,  6075.,  3015.,
        1745.,  1872.,  8098.,  5090.,  4478.,  3240.,  8100., 10800.,
        3216., 14459.,  7180.,  2706.,  3450.,  3510.,  3262.,  8798.,
        1728.,  5304.,  1008.,  1320.,  1865.,  2607.,  2052.,  1153.,
        1310.,  3322.,  3318.,  1206.,  3359.,  6450., 12742., 14544.,
        1130., 17099.,  4361.,  1896.,  2599.,  3960.,  7648.,  1795.,
        2235.,  1833.,  1053.,  2880.,  1170.,  7382., 13176.,  1764.,
        1890.,   922.,   953.,  2025.,   957.,  1252., 15848.,  5841.,
         120.,   513.,  1037.,   672.,   960.,  1087.,  2400.,  3000.,
         839.,  1620.,   588.,  1122.,  1080.,  4199.,  2676.,  2424.,
        3360.,  6000.,  8220.,  7500.,  1966., 19950.,  1789.,  2592.,
        3120., 27000.,  4400.,   583.,  1530.,  4649.,  4494.,  2255.,
        2964., 12672.,  2578.,  5099.,  4346., 18000.,  6113.,  2259.,
        4272.,  4720.,  1485., 20997.,  3075.,  4142.,  3690.,  3840.,
        2622.,  3642.,  3410.,  4800.,  3813.,  4232., 12357.,  6742.,
        3705.,  6899.,  4198.,  3718.,  2573.,  3389.,  3701.,  5652.,
        5901.,  4442.,  2940.,  3856.,  4551.,  4797.,  4444.,  3497.,
        3525.,  2802.,  4197.,  3969.,  7290.,  6643., 12846.,  1259.,
        3442.,  4440.,  6360., 28911.,  4702.,  6480.,  4161.,  4065.,
        5184., 19375., 14931., 19350., 12168.,  3361.,  7497.,  1894.,
        5126.,  3035.,  7695.,  6624., 11457.,  4992.,  5446.,  3738.,
       18270., 15390., 23714., 15201.,  5562.,   969., 10164.,  7335.,
        7830.,  6888.,  2399.,  3213.,  3878.,  8485.,  6583.,  3936.,
        3150.,  4188., 10783., 16650., 11732.,  6912.,  5885.,  6835.,
        7824.,  6400.,  1595., 23515.,  8615.,  8686.,   854.,  8550.,
        8959.,  3273.,  2838., 14826., 14460., 21481.,  2394.,  1687.,
       20022.,  9772.,  8929., 16742., 31243.,   924.,  6140.,  8658.,
        5198.,  8460.,  8575.,  4662.,  4080.,  3665., 17340.,  4112.,
        7176.,  3886.,  8732., 12268.,  7081., 12336.,  3509.,  4202.,
        4061.,  8784.,  4365.,  3232.,  6555.,  4458.,  3910., 15480.,
        4735.,  5454., 20400., 19800.,  4860.,  6343.,  7088.,  9561.,
        4804.,  5400.,  6477.,  6629.,  7764.,  7560.,  9750.,  6561.,
        7524.,  4858.,  4131.,  5599.,  5398.,  5396.,  7050.,  5238.,
        6445., 11596.,  3182.,  4666.,  5410.,  5922.,  3848.,  6267.,
        5308.,  5303.,  3584.,  5449.,  7725.,  5895.,  4104.,  5538.,
        6123.,  3843.,  6338.,  4268.,  5962.,  4480.,  4204.,  5412.,
       12658., 16320.,  3588.,  3692.,  5462.,  5724.,  6319.,  4324.,
        5335.,  8662.,  8424.,  3514.,  3887.,  3912.,  4102.,  4219.,
        3798.,  5507.,  4020.,  6560.,  4078.,  6242., 13446.,  9374.,
        1377.,  2006., 17901., 11745.,  3493., 14621.,  2558.,  3206.,
        3036., 11894.,  2250., 13158.,  3300.,  1647., 20426.,  8160.,
        2504.,  2114.,  3900.,  2673.,  2045.,  2256., 15509.,  4453.,
        4416.,  3860., 10108.,  2187.,  2754., 15327.,  2448.,  3744.,
        5200.,  1115., 20240.,  3648.,  9833.,  6041.,  3062.,  2500.,
        7413.,  6100.,  1683.,  3143., 12131.,  7000., 15000.,  9699.,
        2700., 12046.,  7436.,  9603.,  9889.,  8910., 27900., 11664.,
        6325., 10600., 11410.,  7509.,  5046., 21200.,  4034.,  6370.,
       15055.,  8756.,  3330., 20460.,  4406., 16179.,  6145.,  6010.,
       20564., 17274., 20040., 18680.,  3888.,  3780.,  3548.,  3058.,
        6116., 15042.,  5472.,  4947.,  1911., 13911., 19848.,  5322.,
       14250.,  7473.,  2760., 23058.,   900.,  5760., 12521.,  6048.,
        2722.,  3382.,  2730.,  6336.,  3804.,  6240.,  4364.,  9399.,
        5054.,  1680.,  7673.,  5166.,  4056.,  1776.,  2568.,  4158.,
        1500.,  2850.,  2782.,  2655.,   756.,  9234.,  1918., 12442.,
        1020.,  5445.,  1590., 14987.,  1560.,  2105.,  7470.,  4140.,
        1309.,  1785.,  2088.,  2450.,  3253.,  4019.,  2564.,  2735.,
        9288.,  8812., 13608.,  2376., 20120.,  1291.,  4379.,  9405.,
       14175.,  9391.,  2373.,   630.,  1142.,  1518.,   909.,  1601.,
        2033.,  1112.,  2988.,  1107.,  4501.,  1875.,  2726.,  7466.,
        1385.,  2555.,  2339.,  1860.,  2150.,  2641.,  2430.,  3049.,
        2768.,   891.,  1215.,  1777.,  1295.,   961.,  1746.,  1120.,
        1505.,  2100.,  3475.,  1950.,  1553.,  1326.,  1531.,  1200.,
       10710.,   777., 11552.,   467.,   609.,   840.,  1313.,   603.,
        1661.,  1976.,  6588.,  1134.,   944.,  3354.,  1355.,  1674.,
         643.,  1849.,  1593.,  1440.,  3824.,  3593.,  2652.,   432.,
        2126.,  1296.,   267.,  1019.,  2154.,   486.,   972.,   388.,
        3984.,   260.,  1140.,   719.,  1282.,   297.,   880.,   303.,
         342.,  1114.,   920.,   599.,   539.,   722.,  1070.,  7919.,
        1344.,  8640.,  1081.,  1349.,   540.,   959.,  7056.,   683.,
         842.,  1735.,  1306.,  1056.,  1980.,   480.,  1634.,  2253.,
        8343.,  2177.,  1050.,  1991.,  6528.,  5520.,  5426.,  7200.,
        3391.,  6750.,  2640.,  6895.,  6120.,  7104.,  3542.,  6796.,
        4497.,  5250.,  5670., 36900.,  3957.,  2595.,  5448.,  6896.,
       10337.,  8970.,  7008., 10841.,  9600.,  8945.,  5777.,  9720.,
        4332., 19888.,  3418.,  8316.,  3288.,  5061.,  8376.,  3478.,
        7782.,  8707.,  4357.,  3961.,  4290.,  8679.,  8414.,  3208.,
        4308.,  2205.,  3341.,  9596.,  1906.,  2603.,  2819.,  1614.,
        3043.,  4650.,  8516.,  9504., 11227., 13841.,  2610., 10670.,
        9312.,  5952.,  6605.,  3447.,  1469.,  3732.,  1567., 11997.,
        3683., 10692.,  7620., 14218.,  2996., 12474.,  8010., 11866.,
        6098., 24398., 11640.,  5819., 16855.,  3088., 16038.,  1796.,
        4960.,  9180., 13003., 14340.,  8724., 14940., 17423., 11359.,
        2848.,  8815., 10433., 15660., 13355., 10932.,  1824.,  5722.,
       10796.,  4993.,  9984.,  6210., 13416., 19926., 23998., 10021.,
        5370.,  2878.,  3551.,  3516.,  9624.,  3996., 12780.,  5130.,
        4467.,  4200.,  5746., 12671.,  3420.,  4725.,  5580., 12420.,
        8340., 13040., 13981.,  4395.,  2781.,  4277.,  6420.,  5292.,
        3365.,  6941., 14580.,  3405., 15318.,  6030.,  3985., 15903.,
        2820.,  5280.,  2736.,  1362.,  1688.,  2937.,  3326.,  2379.,
         999.,  2999.,  3348.,  4266.,  2970.,  2907.,  4498.,  5084.,
        3598.,  2023.,  3313.,  4640.,  4820.,  5175.,  2398.,  3106.,
        3456.,  2192.,  1979.,  2517.,  3599.,  2779.,  1123.,  1418.,
        3868.,  2013.,  2554., 12417.,   983.,  2040.,  1837.,  2069.,
        1822., 44996.,  4916.,  3929.,  6633.,  2468.,  4464.,  6472.,
        7350.,  5432.,  6751.,  5076.,  2446.,  3168.,  2847.,  6669.,
        3228.,  4047., 12300.,  6840.,  5240.,  6983.,  4208.,  9716.,
       19711.,  3397.,  4176.,  8902.,  4563.,  6540.,  4680.,  7170.,
        5957.,  1831.,  5294.,  5450.,  5610.,  5827., 19050.,  6579.])

In [29]:
data['Rating'].fillna(data['Rating'].median(), inplace=True)
data['Taxes_and_charges_inr'].fillna(0, inplace=True)
data['Review'].fillna('No Review', inplace=True)

In [30]:
data.isna().sum()

Property_name                     0
Location                          0
Rating                            0
Review                            0
Type_of_stay                    581
Stay_duration_and_group_size      0
price                             0
Taxes_and_charges_inr             0
dtype: int64

In [41]:
data.dropna(inplace =True)

In [42]:
data.isna().sum()

Property_name                   0
Location                        0
Rating                          0
Review                          0
Type_of_stay                    0
Stay_duration_and_group_size    0
price                           0
Taxes_and_charges_inr           0
City                            0
dtype: int64

In [43]:
#here we extract the city name by using location column
data["City"] = data["Location"].apply(lambda x: x.split(",")[-1].strip() if isinstance(x, str) else None)

In [44]:
data

,Property_name,Location,Rating,Review,Type_of_stay,Stay_duration_and_group_size,price,Taxes_and_charges_inr,City
0,olive service apartments rohini,"rohini, new delhi",9.8,exceptional,1×two-bedroom apartmententire apartment•2 bedr...,"5 nights, 10 adults",47814.0,5738.0,new delhi
1,olive service apartments - greater kailash,"greater kailash 1, new delhi",9.0,superb,1×standard two-bedroom apartmententire apartme...,"5 nights, 10 adults",149629.0,26933.0,new delhi
2,anara service apartments - greater kailash par...,new delhi,8.3,very good,1×studio with balconyentire studio•1 kitchen•1...,"5 nights, 10 adults",152620.0,0.0,new delhi
4,bedchambers serviced apartments south extension,new delhi,8.7,fabulous,2×three-bedroom apartment2 entire apartments•6...,"5 nights, 10 adults",144982.0,0.0,new delhi
6,olive serviced apartments - defence colony,new delhi,7.5,good,1×standard studioentire studio•1 bathroom•36m²...,"5 nights, 10 adults",192026.0,34565.0,new delhi
...,...,...,...,...,...,...,...,...,...
1619,northern view haward,shimla,8.8,fabulous,5×deluxe double room5 double bedsfree cancella...,"5 nights, 8 adults, 2 children",23726.0,2847.0,shimla
1620,"treebo greenland, mall road",shimla,5.3,review score,2×economy double room2 extra-large double beds...,"5 nights, 8 adults, 2 children",55575.0,6669.0,shimla
1621,krishna hill stay near mall road,shimla,8.2,very good,2×standard double room2 double bedsfree cancel...,"5 nights, 8 adults, 2 children",26900.0,3228.0,shimla
1622,shimla hills apartments 2bhk,shimla,9.0,superb,2×two-bedroom apartment2 entire apartments•4 b...,"5 nights, 8 adults, 2 children",28000.0,3360.0,shimla
1623,himalayan hideaway,shimla,8.0,very good,1×deluxe family room6 single bedsfree cancella...,"5 nights, 8 adults, 2 children",33725.0,4047.0,shimla

In [39]:
data.shape

(1043, 9)

In [47]:
data.City.unique()

array(['new delhi', 'noida', 'gurgaon', 'agra', 'jaipur', 'varanasi',
       'chicalim', 'arpora', 'calangute', 'goa', 'anjuna', 'mandrem',
       'arambol', 'candolim', 'benaulim', 'vagator', 'verem', 'colva',
       'siolim', 'morjim', 'baga', 'mumbai', 'lonavala', 'leh', 'deskit',
       'kimi', 'hundar', 'chimre', 'munnar', 'alwaye', 'kanthalloor',
       'vythiri', 'sultan bathery', 'wandūr', 'kalpetta', 'alleppey',
       'meppādi', 'ambalavayal', 'wayanad', 'varkala', 'mananthavady',
       'ramakkalmedu', 'cochin', 'kattappana', 'guruvāyūr', 'vagamon',
       'padinjarathara', 'trivandrum', 'nedumbassery', 'thekkady',
       'kuttampuzha', 'athirappilly', 'darjeeling', 'manāli', 'shimla'],
      dtype=object)

In [48]:
data.Location.unique()

array(['rohini, new delhi', 'greater kailash 1, new delhi', 'new delhi',
       'central delhi, new delhi', 'aerocity, new delhi',
       'saket, new delhi', 'south delhi, new delhi',
       'safdarjung enclave, new delhi', 'paharganj, new delhi', 'noida',
       'dlf cyber city, gurgaon', 'new friends colony, new delhi',
       'karol bagh, new delhi', 'mahipalpur, new delhi',
       'chanakyapuri, new delhi', 'west delhi, new delhi', 'agra',
       'taj ganj, agra', 'rakabganj, agra', 'sanjay place, agra',
       'jaipur', 'malviya nagar, jaipur', 'c scheme, jaipur',
       'tonk road, jaipur', 'amer fort road, jaipur',
       'civil lines, jaipur', 'ajmer road, jaipur', 'bani park, jaipur',
       'station road, jaipur', 'amer, jaipur', 'varanasi', 'chicalim',
       'arpora', 'calangute', 'goa', 'anjuna beach, anjuna', 'mandrem',
       'arambol', 'candolim', 'calangute beach, calangute',
       'benaulim beach, benaulim', 'vagator', 'verem', 'anjuna', 'colva',
       'siolim', 'morjim', 'baga', 'western suburbs, mumbai',
       'powai, mumbai', 'south mumbai, mumbai', 'mumbai',
       'central suburbs, mumbai', 'colaba, mumbai', 'santacruz, mumbai',
       'bandra kurla complex, mumbai', 'bandra, mumbai', 'khar, mumbai',
       'lonavala', 'leh', 'deskit', 'kimi', 'hundar', 'chimre', 'munnar',
       'alwaye', 'kanthalloor', 'vythiri', 'sultan bathery', 'wandūr',
       'kalpetta', 'alleppey', 'meppādi', 'ambalavayal', 'wayanad',
       'varkala', 'mananthavady', 'ramakkalmedu', 'fort kochi, cochin',
       'kattappana', 'guruvāyūr', 'vagamon', 'padinjarathara',
       'trivandrum', 'nedumbassery', 'thekkady', 'kuttampuzha',
       'athirappilly', 'darjeeling', 'manāli', 'aleo, manāli',
       'old manali, manāli', 'new manali, manāli', 'shimla'], dtype=object)

In [49]:
'''Stay_duration_and_group_size: by using this column i create a 2 more column for the number of adults and children 
to make better understanding about data so for that i use lambda function '''

x = lambda x : x.str.split(" ").str[2]
data[["No_Of_Adults"]] =data[["Stay_duration_and_group_size"]].apply(x).astype(int)
y = lambda x : x.str.split(" ").str[4]
data[["No_Of_Children"]] =data[["Stay_duration_and_group_size"]].apply(y)

In [50]:
data

,Property_name,Location,Rating,Review,Type_of_stay,Stay_duration_and_group_size,price,Taxes_and_charges_inr,City,No_Of_Adults,No_Of_Children
0,olive service apartments rohini,"rohini, new delhi",9.8,exceptional,1×two-bedroom apartmententire apartment•2 bedr...,"5 nights, 10 adults",47814.0,5738.0,new delhi,10,NaN
1,olive service apartments - greater kailash,"greater kailash 1, new delhi",9.0,superb,1×standard two-bedroom apartmententire apartme...,"5 nights, 10 adults",149629.0,26933.0,new delhi,10,NaN
2,anara service apartments - greater kailash par...,new delhi,8.3,very good,1×studio with balconyentire studio•1 kitchen•1...,"5 nights, 10 adults",152620.0,0.0,new delhi,10,NaN
4,bedchambers serviced apartments south extension,new delhi,8.7,fabulous,2×three-bedroom apartment2 entire apartments•6...,"5 nights, 10 adults",144982.0,0.0,new delhi,10,NaN
6,olive serviced apartments - defence colony,new delhi,7.5,good,1×standard studioentire studio•1 bathroom•36m²...,"5 nights, 10 adults",192026.0,34565.0,new delhi,10,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1619,northern view haward,shimla,8.8,fabulous,5×deluxe double room5 double bedsfree cancella...,"5 nights, 8 adults, 2 children",23726.0,2847.0,shimla,8,2
1620,"treebo greenland, mall road",shimla,5.3,review score,2×economy double room2 extra-large double beds...,"5 nights, 8 adults, 2 children",55575.0,6669.0,shimla,8,2
1621,krishna hill stay near mall road,shimla,8.2,very good,2×standard double room2 double bedsfree cancel...,"5 nights, 8 adults, 2 children",26900.0,3228.0,shimla,8,2
1622,shimla hills apartments 2bhk,shimla,9.0,superb,2×two-bedroom apartment2 entire apartments•4 b...,"5 nights, 8 adults, 2 children",28000.0,3360.0,shimla,8,2
1623,himalayan hideaway,shimla,8.0,very good,1×deluxe family room6 single bedsfree cancella...,"5 nights, 8 adults, 2 children",33725.0,4047.0,shimla,8,2

In [51]:
#so this column having some null values so i replace them with 0
data[["No_Of_Children"]] = data[["No_Of_Children"]].fillna(0).astype(int)

In [52]:
#Drop stay_duration_And_group_size column
data.drop("Stay_duration_and_group_size",axis = 1 ,inplace = True)

In [53]:
#create a new column Final_Price by using the Original_price and Taxes_and_charges_inr columns 
data["Final_Price"] =data["price"]+data["Taxes_and_charges_inr"]

In [54]:
data

,Property_name,Location,Rating,Review,Type_of_stay,price,Taxes_and_charges_inr,City,No_Of_Adults,No_Of_Children,Final_Price
0,olive service apartments rohini,"rohini, new delhi",9.8,exceptional,1×two-bedroom apartmententire apartment•2 bedr...,47814.0,5738.0,new delhi,10,0,53552.0
1,olive service apartments - greater kailash,"greater kailash 1, new delhi",9.0,superb,1×standard two-bedroom apartmententire apartme...,149629.0,26933.0,new delhi,10,0,176562.0
2,anara service apartments - greater kailash par...,new delhi,8.3,very good,1×studio with balconyentire studio•1 kitchen•1...,152620.0,0.0,new delhi,10,0,152620.0
4,bedchambers serviced apartments south extension,new delhi,8.7,fabulous,2×three-bedroom apartment2 entire apartments•6...,144982.0,0.0,new delhi,10,0,144982.0
6,olive serviced apartments - defence colony,new delhi,7.5,good,1×standard studioentire studio•1 bathroom•36m²...,192026.0,34565.0,new delhi,10,0,226591.0
...,...,...,...,...,...,...,...,...,...,...,...
1619,northern view haward,shimla,8.8,fabulous,5×deluxe double room5 double bedsfree cancella...,23726.0,2847.0,shimla,8,2,26573.0
1620,"treebo greenland, mall road",shimla,5.3,review score,2×economy double room2 extra-large double beds...,55575.0,6669.0,shimla,8,2,62244.0
1621,krishna hill stay near mall road,shimla,8.2,very good,2×standard double room2 double bedsfree cancel...,26900.0,3228.0,shimla,8,2,30128.0
1622,shimla hills apartments 2bhk,shimla,9.0,superb,2×two-bedroom apartment2 entire apartments•4 b...,28000.0,3360.0,shimla,8,2,31360.0
1623,himalayan hideaway,shimla,8.0,very good,1×deluxe family room6 single bedsfree cancella...,33725.0,4047.0,shimla,8,2,37772.0

In [55]:
#here I create a new column recommended_for
recommend = lambda x : x==0
data["Recommended for"] = data["No_Of_Children"].apply(recommend).astype(str)

In [59]:
data["Recommended for"] =data["Recommended for"].replace("True","Recommended for Friends Trip").str.lower()
data["Recommended for"] =data["Recommended for"].replace("false","Recommended for Family Trip").str.lower()

In [60]:
data.groupby("No_Of_Children")[["Recommended for"]].sum()

                                                  Recommended for
No_Of_Children
0               recommended for friends triprecommended for fr...
1               recommended for family triprecommended for fam...
2               recommended for family triprecommended for fam...
4               recommended for family triprecommended for fam...

In [61]:
data

,Property_name,Location,Rating,Review,Type_of_stay,price,Taxes_and_charges_inr,City,No_Of_Adults,No_Of_Children,Final_Price,Recommended for
0,olive service apartments rohini,"rohini, new delhi",9.8,exceptional,1×two-bedroom apartmententire apartment•2 bedr...,47814.0,5738.0,new delhi,10,0,53552.0,recommended for friends trip
1,olive service apartments - greater kailash,"greater kailash 1, new delhi",9.0,superb,1×standard two-bedroom apartmententire apartme...,149629.0,26933.0,new delhi,10,0,176562.0,recommended for friends trip
2,anara service apartments - greater kailash par...,new delhi,8.3,very good,1×studio with balconyentire studio•1 kitchen•1...,152620.0,0.0,new delhi,10,0,152620.0,recommended for friends trip
4,bedchambers serviced apartments south extension,new delhi,8.7,fabulous,2×three-bedroom apartment2 entire apartments•6...,144982.0,0.0,new delhi,10,0,144982.0,recommended for friends trip
6,olive serviced apartments - defence colony,new delhi,7.5,good,1×standard studioentire studio•1 bathroom•36m²...,192026.0,34565.0,new delhi,10,0,226591.0,recommended for friends trip
...,...,...,...,...,...,...,...,...,...,...,...,...
1619,northern view haward,shimla,8.8,fabulous,5×deluxe double room5 double bedsfree cancella...,23726.0,2847.0,shimla,8,2,26573.0,recommended for family trip
1620,"treebo greenland, mall road",shimla,5.3,review score,2×economy double room2 extra-large double beds...,55575.0,6669.0,shimla,8,2,62244.0,recommended for family trip
1621,krishna hill stay near mall road,shimla,8.2,very good,2×standard double room2 double bedsfree cancel...,26900.0,3228.0,shimla,8,2,30128.0,recommended for family trip
1622,shimla hills apartments 2bhk,shimla,9.0,superb,2×two-bedroom apartment2 entire apartments•4 b...,28000.0,3360.0,shimla,8,2,31360.0,recommended for family trip
1623,himalayan hideaway,shimla,8.0,very good,1×deluxe family room6 single bedsfree cancella...,33725.0,4047.0,shimla,8,2,37772.0,recommended for family trip

In [62]:
data.duplicated().sum()

76

In [63]:
data.drop_duplicates(inplace =True)

In [64]:
data.shape

(967, 12)

In [65]:
data.isna().sum()

Property_name            0
Location                 0
Rating                   0
Review                   0
Type_of_stay             0
price                    0
Taxes_and_charges_inr    0
City                     0
No_Of_Adults             0
No_Of_Children           0
Final_Price              0
Recommended for          0
dtype: int64

In [72]:
data.Type_of_stay.unique()

array(['1×two-bedroom apartmententire apartment',
       '1×standard two-bedroom apartmententire apartment',
       '1×studio with balconyentire studio',
       '2×three-bedroom apartment2 entire apartments',
       '1×standard studioentire studio', '1×apartmententire apartment',
       '2×two-bedroom apartment2 entire apartments',
       '1×three-bedroom standard apartmententire apartment',
       '1×three-bedroom apartment with balconyentire apartment',
       '1×three-bedroom superior apartmententire apartment',
       '1×safdarjung enclave-3bhk apartment with wifientire apartment',
       '4×premier studio with in-room air purifier4 entire studios',
       '5×superior studio with airport pickup5 entire studios',
       '5×deluxe studio5 entire studios',
       '5×superior studio5 entire studios',
       '4×luxury studio apartment with kitchenette( new delhi city tour\xa0\xa0included\xa0\xa0)4 entire apartments',
       '1×one-bedroom apartmententire apartment',
       '1×king studioentire studio',
       '3×one-bedroom apartment3 entire apartments',
       '4×studio apartment4 extra-large double bedsfree cancellation',
       '5×boutique room _non view5 entire studios',
       '1×family room2 beds (1 single, 1 large double) ',
       '2×deluxe double room2 single bedsfree cancellationno prepayment needed– pay at the property',
       '2×king room2 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room (2 adults + 1 child)5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×superior king room5 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room5 double beds ',
       '5×double room5 double bedsfree cancellationno prepayment needed– pay at the property',
       '1×deluxe room1 double bedfree cancellationno prepayment needed– pay at the property',
       '1×standard double room with fan1 double bedfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room (2 adults + 1 child)5 double bedsfree cancellationno prepayment needed– pay at the property',
       '1×quadruple room2 beds (1 single, 1 extra-large double)free cancellationno prepayment needed– pay at the property',
       '5×deluxe room5 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×standard king room5 double bedsfree cancellationno prepayment needed– pay at the property',
       '2×budget double room2 double bedsfree cancellationno prepayment needed– pay at the property',
       '4×classic triple room4 large double bedsfree cancellation',
       '4×double room4 double bedsfree cancellationno prepayment needed– pay at the property',
       '4×classic triple room4 large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×three-bedroom deluxe apartmententire apartment',
       '1×superior double roommultiple bed typesfree cancellation',
       '4×double room with garden view4 extra-large double beds',
       '3×deluxe triple room6 beds (3 singles, 3 large doubles)free cancellationno prepayment needed– pay at the property',
       '1×budget double room2 beds (1 single, 1 double)free cancellationno prepayment needed– pay at the property',
       '1×standard triple room2 beds (1 double, 1 futon)no prepayment needed– pay at the property',
       '1×deluxe queen room1 double bedfree cancellationno prepayment needed– pay at the property',
       '1×deluxe room1 double bedfree cancellation',
       '2×deluxe double room2 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×superior double room5 extra-large double bedsfree stay for your childfree cancellation',
       '5×deluxe double room with balcony (early check-in and late check-out, subject to availability)5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×deluxe queen room with two queen beds2 double bedsfree stay for your childfree cancellationno prepayment needed– pay at the property',
       '1×deluxe double room1 extra-large double bedfree stay for your child',
       '1×deluxe double room1 extra-large double bedfree cancellationno prepayment needed– pay at the property',
       '1×budget double room1 single bedfree stay for your childfree cancellation',
       '4×deluxe room4 extra-large double beds',
       '1×deluxe family room2 beds (1 single, 1 extra-large double)free cancellation',
       '5×double room with private bathroom5 large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×deluxe triple room2 beds (1 extra-large double, 1 sofa bed)',
       '4×deluxe double room (2 adults + 1 child)4 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×twin room2 single bedsfree cancellation',
       '1×standard double room1 extra-large double bedfree cancellation',
       '2×double or twin room with balconychoice of beds: singles or large doublefree cancellation',
       '2×deluxe king room2 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '3×mixed dormitory room3 shared dormitory rooms15 beds (3 singles, 12 bunk beds) ',
       '1×standard double room1 double bedfree cancellationno prepayment needed– pay at the property',
       '1×family room2 beds (1 single, 1 double)free cancellationno prepayment needed– pay at the property',
       '4×standard room with two single beds8 single beds',
       '1×deluxe quadruple room2 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '2×standard double room with fan2 double bedsfree cancellationno prepayment needed– pay at the property',
       '4×double room with private bathroom4 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×double room5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe garden view room5 double bedsfree cancellation',
       '2×bed in 6-bed mixed dormitory room2 beds in dormitories2 bunk bedsfree cancellation',
       '4×double room with private bathroom4 large double bedsfree cancellationno prepayment needed– pay at the property',
       '2×deluxe twin room4 single bedsfree cancellation',
       '10×bed in 8-bed mixed dormitory room10 beds in dormitories10 single bedsfree cancellation',
       '4×superior room twin bed8 single bedsfree cancellationno prepayment needed– pay at the property',
       '1×deluxe family room2 beds (1 single, 1 extra-large double)free cancellationno prepayment needed– pay at the property',
       '2×standard double roomchoice of beds: large double or singlesfree cancellation',
       '4×deluxe king room4 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '2×triple room24 double bedsfree cancellationno prepayment needed– pay at the property',
       '4×standard room with two single beds8 single bedsfree cancellationno prepayment needed– pay at the property',
       '4×deluxe twin room with 15% discount on food, beverages and spa | 1+1 on select alcoholic beverages (6:00pm to 8:00pm at onyx bar)8 single bedsfree cancellation',
       '1×superior room king bed1 extra-large double bedfree cancellationno prepayment needed– pay at the property',
       '1×family room with private bathroom2 single bedsfree cancellationno prepayment needed– pay at the property',
       '4×mughal room with garden view4 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '4×mixed dormitory room4 shared dormitory rooms20 beds (4 singles, 16 bunk beds) ',
       '5×executive double with 10% discount on food & beverages5 double bedsfree cancellation',
       '4×deluxe double room4 double bedsfree cancellationno prepayment needed– pay at the property',
       '4×standard double room4 large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×deluxe king room with city view & 20% off on food & beverages and 2 pieces of ironing daily1 extra-large double bed',
       '1×deluxe double room1 extra-large double bed',
       '5×standard room with two single beds10 single bedsfree cancellationno prepayment needed– pay at the property',
       '5×standard double room with fan5 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe king room5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×standard double room5 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe twin room with 15% discount on food, beverages and spa | 1+1 on select alcoholic beverages (6:00pm to 8:00pm at onyx bar)10 single bedsfree cancellation',
       '1×deluxe double room with balconymultiple bed typesfree cancellation',
       '5×mughal room with garden view5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×double room with private bathroom5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×deluxe double room1 large double bedfree cancellation',
       '5×deluxe double room (2 adults + 1 child)5 large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×deluxe twin room with city view & 20% off on food & beverages and 2 pieces of ironing daily2 single beds',
       '5×standard room5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room with bath5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×standard roomchoice of beds: singles or double',
       '5×king room5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room5 double bedsfree cancellationno prepayment needed– pay at the property',
       '2×deluxe double room (2 adults + 1 child)2 double bedsfree cancellationno prepayment needed– pay at the property',
       '1×double room1 large double bedfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room5 large double bedsfree cancellationno prepayment needed– pay at the property',
       '4×double room4 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×standard triple room2 beds (1 double, 1 futon)free cancellationno prepayment needed– pay at the property',
       '5×deluxe double or twin room with garden view5 extra-large double beds',
       '3×double room3 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '2×premium room with european style décor and city view2 extra-large double bedsfree cancellation',
       '1×superior double room1 extra-large double bedfree cancellationno prepayment needed– pay at the property',
       '4×twin room8 beds (4 singles, 4 sofa beds)',
       '4×single bed in mixed dormitory room4 beds in dormitories4 single bedsfree cancellation',
       '1×quadruple room2 double bedsfree cancellationno prepayment needed– pay at the property',
       '1×deluxe family suite2 double bedsfree cancellationno prepayment needed– pay at the property',
       '3×double room3 large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×budget double room1 double bedfree cancellationno prepayment needed– pay at the property',
       '5×standard twin room10 single beds',
       '2×deluxe double room-2 double bedsfree cancellationno prepayment needed– pay at the property',
       '1×budget double room2 single bedsfree cancellation',
       '1×semi deluxe double room with fan1 double bedfree cancellationno prepayment needed– pay at the property',
       '1×deluxe double room1 double bedfree cancellationno prepayment needed– pay at the property',
       '10×bed in 8-bed mixed dormitory room10 beds in dormitories10 bunk beds',
       '5×standard twin room10 single bedsfree cancellationno prepayment needed– pay at the property',
       '1×king room1 extra-large double bed',
       '5×double room5 double beds ',
       '3×royal deluxe with free pick up on arrival only from train or bus stationchoice of beds: extra-large double or singlesfree cancellationno prepayment needed– pay at the property',
       '2×standard double room2 double bedsfree cancellation',
       '5×twin room10 beds (5 singles, 5 sofa beds)',
       '5×classic triple room5 large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×double room5 large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe room5 double beds',
       '1×deluxe quadruple room2 beds (1 double, 1 bunk bed)',
       '5×deluxe double or twin roomchoice of beds: singles or large doublefree cancellationno prepayment needed– pay at the property',
       '1×double room with terrace2 single bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×double room5 double beds',
       '2×premier triple room with daybed4 beds (2 doubles, 2 sofa beds)free cancellation',
       '5×deluxe double room with complimentary airport pick upchoice of beds: extra-large double or singlesfree cancellation',
       '5×standard double room5 large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×budget double room5 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe room5 double bedsfree cancellation',
       '2×twin room4 beds (2 singles, 2 sofa beds)',
       '2×classic triple room2 large double bedsfree cancellationno prepayment needed– pay at the property',
       '2×standard twin room4 single beds',
       '2×standard room: (enjoy happy hours 1+1 offer on alcoholic beverages 12 pm-6 pm  (except dragon house), soft beverages ,laundry service)choice of beds: extra-large double or singlesfree cancellation',
       '2×superior garden view with twin bed(20% discount on food and soft beverages, 20% discount on spa,buy 1 get 1 on select brands at madeira bar between 4 pm - 10 pm)choice of beds: singles or singlesfree cancellationno prepayment needed– pay at the property',
       '2×double room - no view/executive club2 double bedsfree cancellationno prepayment needed– pay at the property',
       '2×guest room twin beds city view : enjoy 15% off on food & soft beverages and 1+1 on select alcoholic beverages at twenty one bar & café (4:00 pm to 8:00 pm)4 single bedsfree cancellationno prepayment needed– pay at the property',
       '2×classic twin room4 single bedsfree cancellationno prepayment needed– pay at the property',
       '2×suite2 private suites',
       '2×double room4 beds (2 singles, 2 doubles)free cancellationno prepayment needed– pay at the property',
       '2×double room with private bathroom2 double bedsfree cancellationno prepayment needed– pay at the property',
       '2×deluxe room2 double bedsfree cancellationno prepayment needed– pay at the property',
       '2×deluxe room (2 adults + 1 child)2 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '2×standard double room2 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×superior double room5 large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×double room25 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×double room with private bathroom5 double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room (2 adults + 1 child)10 double bedsfree cancellationno prepayment needed– pay at the property',
       '2×quadruple room4 double beds ',
       '1×double room with balcony2 single bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe room (2 adults + 1 child)5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×family roommultiple bed typesfree cancellationno prepayment needed– pay at the property',
       '1×superior king room1 large double bedfree cancellationno prepayment needed– pay at the property',
       '5×standard room with balconychoice of beds: large double or singlesfree cancellationno prepayment needed– pay at the property',
       '5×deluxe king room5 double bedsfree cancellation',
       '1×two-bedroom houseentire holiday home',
       '4×suite4 private suites',
       '1×double room2 beds (1 single, 1 double)free cancellation',
       '2×deluxe king room4 double bedsfree cancellation',
       '5×standard double room5 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×king room5 large double bedsfree cancellationno prepayment needed– pay at the property',
       '1×single room with shared shower and toilet1 single bedfree cancellationno prepayment needed– pay at the property',
       '1×double room4 beds (3 singles, 1 large double)free cancellationno prepayment needed– pay at the property',
       '1×deluxe double room with balcony1 extra-large double bedfree cancellation',
       '4×triple room with private bathroom8 beds (4 singles, 4 large doubles)free cancellation',
       '4×standard double room4 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '4×deluxe room4 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '4×deluxe double roomchoice of beds: extra-large double or singlesfree cancellationno prepayment needed– pay at the property',
       '4×economy double room4 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '4×deluxe double room4 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room with balcony5 double bedsfree cancellationno prepayment needed– pay at the property',
       '2×double room2 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '2×deluxe double room2 extra-large double bedsfree cancellation',
       '5×standard double room5 extra-large double bedsfree stay for your childfree cancellationno prepayment needed– pay at the property',
       '5×superior double room5 large double bedsfree stay for your childfree cancellationno prepayment needed– pay at the property',
       '5×standard double room5 double bedsfree stay for your childfree cancellationno prepayment needed– pay at the property',
       '5×standard room with balconychoice of beds: large double or singlesfree stay for your childfree cancellationno prepayment needed– pay at the property',
       '5×classic triple room5 large double bedsfree stay for your childfree cancellationno prepayment needed– pay at the property',
       '5×deluxe double room5 extra-large double bedsfree stay for your childfree cancellationno prepayment needed– pay at the property',
       '1×double or twin room1 extra-large double bedfree cancellationno prepayment needed– pay at the property',
       '5×one-bedroom apartment5 entire apartments',
       '2×apartment with balcony2 entire apartments',
       '1×double room with garden view2 double bedsfree cancellation',
       '4×cottage with garden view4 entire bungalows',
       '1×1bhk apartment with balconyentire apartment',
       '1×superior double room1 double bedfree cancellation',
       '1×one-bedroom apartment with garden viewentire apartment',
       '3×junior suite3 private suites3 extra-large double bedsfree cancellation',
       '4×executive room4 large double bedsfree cancellation',
       '3×deluxe room3 extra-large double bedsfree cancellationno prepayment needed– pay at the property',
       '3×executive suite3 private suites3 extra-large double bedsfree cancellation',

In [71]:
x = lambda x : x.str.split("•").str[0]
data[["Type_of_stay"]] = data[["Type_of_stay"]].apply(x)

In [73]:
data

,Property_name,Location,Rating,Review,Type_of_stay,price,Taxes_and_charges_inr,City,No_Of_Adults,No_Of_Children,Final_Price,Recommended for
0,olive service apartments rohini,"rohini, new delhi",9.8,exceptional,1×two-bedroom apartmententire apartment,47814.0,5738.0,new delhi,10,0,53552.0,recommended for friends trip
1,olive service apartments - greater kailash,"greater kailash 1, new delhi",9.0,superb,1×standard two-bedroom apartmententire apartment,149629.0,26933.0,new delhi,10,0,176562.0,recommended for friends trip
2,anara service apartments - greater kailash par...,new delhi,8.3,very good,1×studio with balconyentire studio,152620.0,0.0,new delhi,10,0,152620.0,recommended for friends trip
4,bedchambers serviced apartments south extension,new delhi,8.7,fabulous,2×three-bedroom apartment2 entire apartments,144982.0,0.0,new delhi,10,0,144982.0,recommended for friends trip
6,olive serviced apartments - defence colony,new delhi,7.5,good,1×standard studioentire studio,192026.0,34565.0,new delhi,10,0,226591.0,recommended for friends trip
...,...,...,...,...,...,...,...,...,...,...,...,...
1619,northern view haward,shimla,8.8,fabulous,5×deluxe double room5 double bedsfree cancella...,23726.0,2847.0,shimla,8,2,26573.0,recommended for family trip
1620,"treebo greenland, mall road",shimla,5.3,review score,2×economy double room2 extra-large double beds...,55575.0,6669.0,shimla,8,2,62244.0,recommended for family trip
1621,krishna hill stay near mall road,shimla,8.2,very good,2×standard double room2 double bedsfree cancel...,26900.0,3228.0,shimla,8,2,30128.0,recommended for family trip
1622,shimla hills apartments 2bhk,shimla,9.0,superb,2×two-bedroom apartment2 entire apartments,28000.0,3360.0,shimla,8,2,31360.0,recommended for family trip
1623,himalayan hideaway,shimla,8.0,very good,1×deluxe family room6 single bedsfree cancella...,33725.0,4047.0,shimla,8,2,37772.0,recommended for family trip

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 967 entries, 0 to 1623
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Property_name          967 non-null    object
 1   Location               967 non-null    object
 2   Rating                 967 non-null    float64
 3   Review                 967 non-null    object
 4   Type_of_stay           967 non-null    object
 5   price                  967 non-null    float64
 6   Taxes_and_charges_inr  967 non-null    float64
 7   City                   967 non-null    object
 8   No_Of_Adults           967 non-null    int32
 9   No_Of_Children         967 non-null    int32
 10  Final_Price            967 non-null    float64
 11  Recommended for        967 non-null    object
dtypes: float64(4), int32(2), object(6)
memory usage: 90.7+ KB

In [ ]:
x = lambda x : x.str.split("cancellationno prepayment needed– pay at the property").str[0]
data[["Type_of_stay"]] = data[["Type_of_stay"]].apply(x)

In [76]:
data.to_csv("Cleaned_Booking.com_data")

In [77]:
data

,Property_name,Location,Rating,Review,Type_of_stay,price,Taxes_and_charges_inr,City,No_Of_Adults,No_Of_Children,Final_Price,Recommended for
0,olive service apartments rohini,"rohini, new delhi",9.8,exceptional,1×two-bedroom apartmententire apartment,47814.0,5738.0,new delhi,10,0,53552.0,recommended for friends trip
1,olive service apartments - greater kailash,"greater kailash 1, new delhi",9.0,superb,1×standard two-bedroom apartmententire apartment,149629.0,26933.0,new delhi,10,0,176562.0,recommended for friends trip
2,anara service apartments - greater kailash par...,new delhi,8.3,very good,1×studio with balconyentire studio,152620.0,0.0,new delhi,10,0,152620.0,recommended for friends trip
4,bedchambers serviced apartments south extension,new delhi,8.7,fabulous,2×three-bedroom apartment2 entire apartments,144982.0,0.0,new delhi,10,0,144982.0,recommended for friends trip
6,olive serviced apartments - defence colony,new delhi,7.5,good,1×standard studioentire studio,192026.0,34565.0,new delhi,10,0,226591.0,recommended for friends trip
...,...,...,...,...,...,...,...,...,...,...,...,...
1619,northern view haward,shimla,8.8,fabulous,5×deluxe double room5 double bedsfree cancella...,23726.0,2847.0,shimla,8,2,26573.0,recommended for family trip
1620,"treebo greenland, mall road",shimla,5.3,review score,2×economy double room2 extra-large double beds...,55575.0,6669.0,shimla,8,2,62244.0,recommended for family trip
1621,krishna hill stay near mall road,shimla,8.2,very good,2×standard double room2 double bedsfree cancel...,26900.0,3228.0,shimla,8,2,30128.0,recommended for family trip
1622,shimla hills apartments 2bhk,shimla,9.0,superb,2×two-bedroom apartment2 entire apartments,28000.0,3360.0,shimla,8,2,31360.0,recommended for family trip
1623,himalayan hideaway,shimla,8.0,very good,1×deluxe family room6 single bedsfree cancella...,33725.0,4047.0,shimla,8,2,37772.0,recommended for family trip

In [78]:
data.shape

(967, 12)